### ISSUE TITLE
It does not recognize documentation on same line

### ISSUE THREAD

**Issue by Vild** [dlang-community/D-Scanner#499]
`dscanner --version` = `v0.4.0 0b064a000ec10b9fe16d6a762c1f1927d532ef7d`

Same as #342.

Example:
```d
module test;

///
struct BugBase {}

///
struct Bug {
	BugBase base; ///
	alias base this;

	ubyte val1; ///
	private ubyte reserved;
	ushort val2; ///
	ushort val3; ///
}
```
Output from `dscanner --report test.d`:
- Public declaration 'base' is undocumented.
- Public declaration 'val2' is undocumented.

I expected that this shouldn't output any errors, or if empty documentation comments on field are disallowed, complain about all the field. 
Also a weird artifact that happens now, is if I add some text to the `base` documentation comment, it complains about `val1` instead of `base`.

**Comment by wilzbach** [comment]
> I expected that this shouldn't output any errors, or if empty documentation comments on field are disallowed, complain about all the field.

The Ddoc spec allows this and I just had a brief look at the check and it looks like it's correctly checking this:

```d
	override void visit(const VariableDeclaration variable)
	{
		if (!currentIsInteresting() || variable.comment.ptr !is null)
```

I will have more time to look into this tomorrow, but if you have want to have a look yourself:
https://github.com/dlang-community/D-Scanner/blob/master/src/analysis/undocumented.d

and I recommend applying ` sed 's/dparse_verbose/StdLoggerDisableWarning/' -i makefile` as otherwise the debug build won't be helpful ;-)

**Comment by CyberShadow** [comment]
> Example:

These seem to work now.

Though, this doesn't:

```d
void fun() {} /// Test
```
