### ISSUE TITLE
versioned unittests don't qualify as publicly documented examples

### ISSUE THREAD

**Issue by joakim-noah** [dlang-community/D-Scanner#654]
Ran into this with dlang/phobos#6525, that pull is blocked on this. I'll see about fixing it.

**Comment by joakim-noah** [comment]
He should read the docs then, as this example won't work without floating-point hardware anyway, as the struct docs lay out. I suppose if we put the version block inside the unit test, then it will again warn the user, but that seems redundant.

Dunno, let me know which you prefer.

**Comment by joakim-noah** [comment]
Seb, just let me know if you prefer the version statements to be put inside the test blocks or not and we'll move forward.

**Comment by wilzbach** [comment]
Sorry I'm getting way too many mails nowadays :/
I actually don't have a strong opinion on this, so I would merge a PR that adds support for this. I won't have much time to do this myself in the next weeks though.

Maybe we can just add the hard-coded set of versions which are supported by run.dlang.io? Because otherwise the run button won't work.

**Comment by joakim-noah** [comment]
No, that's fine, we'll just put the versions inside for documented examples.
