### ISSUE TITLE
0.6.0 ~ DScanner does not seem to scan more than a depth of 1 module

### ISSUE THREAD

**Issue by Valmar33** [dlang-community/D-Scanner#751]
This is with VSCode master, using distro-provided DScanner.

Namely, if I'm just importing `bindbc.sdl` with `"d.projectImportPaths": ["Sources/ThirdParty/bindbc-sdl/source"]` then DScanner doesn't seem to find everything imported by the `package.d` file, which forces me to have to import the various modules manually for anything to be scanned, such as `bindbc.sdl.bind.sdl` for example. It gets tedious and annoying to do so.

Just tired right now, so I hope this description is clear enough.

**Comment by LaurentTreguier** [comment]
I tried `dub run dscanner -- -S .` at the root of a new dub project containing a `a.b.c.lib` module that wasn't referenced in `app.d`, and it returned warnings from that module.
Maybe this is due to how [workspace-d](https://github.com/Pure-D/workspace-d) works; assuming you're using [code-d](https://github.com/Pure-D/code-d). It could be using D-Scanner selectively on files that are imported only.

**Comment by Basile-z** [comment]
not directly a D-Scanner issue then i presume ?
